name: web-example-release
on:
  workflow_dispatch: # Allows manual triggering
  release:
    types: [published] # Triggers when a release is published

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout input branch from github
        uses: actions/checkout@v4.1.1
      - name: Flutter action
        uses: subosito/flutter-action@v2.13.0
        with:
          flutter-version: '3.32.5'
          cache: true
          cache-key: 'flutter-3.32.5-stable'
          cache-path: '${{ runner.tool_cache }}/flutter/3.32.5-stable'
          pub-cache-key: 'flutter-pub-3.32.5-stable'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Project Clean Up
        run: flutter clean && flutter pub get
      - name: Build Web App
        run: cd example && flutter build web --base-href="/showcaseview/"
      - name: Upload Web Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: 'example/build/web'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
